import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { CartProvider } from "./context/CartContext";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "E-Tech Rebuilt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="d-flex flex-column min-vh-100">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex flex-column flex-grow-1`}
      >
        <CartProvider>
          <div className="flex-grow-1">{children}</div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
